import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    rcontainer: {
        flex: 1,
        zIndex: 2,
    },
    uploadImageButton: {
        borderWidth: 2,
        borderRadius: 50,
        borderColor: '#DAAC50',
        borderStyle: 'dashed',
        marginTop: 20,
        width: 100,
        height: 100,
        alignSelf: 'center',
        fontFamily: "Montserrat-Regular",
    },
    rbackgroundImage: {
        flex: 1,
        resizeMode: 'cover', // or 'stretch'
        flexGrow: 1,
        fontFamily: "Montserrat-Regular",
    },

    rboxcont: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        marginTop: 30,
        width: '100%',
        alignItems: 'center',
        alignSelf: 'center',
        fontFamily: "Montserrat-Regular",
    },
    transparentInputContainer: {
        marginLeft: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 5,
        borderBottomWidth: 0,
        paddingRight: 15,
        paddingLeft: 15,
        marginTop: 20,
        fontFamily: "Montserrat-Regular",
    },
    inputFieldStyle: {
        fontSize: 14,
        color: 'white',
        fontFamily: "Montserrat-Regular",
    },
    errorTextStyle: {
        fontSize: 12,
        color: '#ffffff',
        opacity: 0.5,
        fontFamily: "Montserrat-Regular",
    },
    signInButtonStyle: {
        marginBottom: 10,
        borderRadius: 5,
        marginTop: 20,
        backgroundColor: '#3A5E8A',
        fontFamily: "Montserrat-Regular",
    },
    containerPf: {
        // flex: 1,
        // textAlign: 'center',
        // flexGrow: 1,
        // fontFamily: "Montserrat-Regular",
    },
    buttonPf: {
        backgroundColor: '#1C2E51',
        color: '#ffffff',
        marginBottom: 30,
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        width: '86%',
        // height: 64,
        // marginLeft:'7%',
        alignSelf: 'center',
        borderRadius: 5,
        fontFamily: "Montserrat-Regular",
    },
    buttonPf1: {
        backgroundColor: '#1C2E51',
        color: '#ffffff',
        marginBottom: 30,
        alignContent: 'center',
        justifyContent: 'center',
        width: '86%',
        // marginLeft:'7%',
        marginTop: 40,
        alignSelf: 'center',
        borderRadius: 5,
        fontFamily: "Montserrat-Regular",
    },
    whiteColor: {
        color: '#ffffff',
        fontSize: 18,
        marginTop: 20,
        width: '86%',
        marginLeft: '7%',
        opacity: 0.7,
        fontFamily: "Montserrat-Regular",
    },
    whiteColor1: {
        color: '#ffffff',
        fontSize: 17,
        width: '86%',
        marginLeft: '7%',
        fontFamily: "Montserrat-Regular",
    },
    buttonContinue: {
        backgroundColor: 'transparent',
        color: '#ffffff',
        width: '86%',
        marginLeft: '7%',
        marginTop: 20,
        fontFamily: "Montserrat-Regular",
    },
    buttonMyProject: {
        // backgroundColor:'#3A801D',
        backgroundColor: '#E6C44E66',
        borderColor: '#E6C44E66',
        borderWidth: 1,
        color: '#ffffff',
        alignContent: 'center',
        justifyContent: 'center',
        width: '86%',
        // marginLeft:'7%',
        marginTop: 10,
        alignSelf: 'center',
        borderRadius: 5,
        opacity: 0.8,
        fontFamily: "Montserrat-Regular",
    },
    textWhite: {
        color: '#ffffff',
        // alignItems: 'center',
        // justifyContent: 'center',
        // alignContent: 'center',
        textAlign: 'center',
        alignSelf: 'center',
        fontSize: 14,
        fontFamily: "Montserrat-Regular",
    },
    orText: {
        alignSelf: 'center',
        fontSize: 14,
        color: '#dddddd',
        fontFamily: "Montserrat-Regular",

    },
    removeImageButtonStyle: {
        position: 'absolute',
        top: 0,
        right: -5,
        flex: 1,
        alignContent: 'center',
        justifyContent: 'center',
        borderRadius: 15,
        width: 30,
        height: 30,
        backgroundColor: 'red',
        paddingRight: 0,
        paddingLeft: 0,
        paddingTop: 0,
        paddingBottom: 0,
        fontFamily: "Montserrat-Regular",
    },
    changeImageButtonStyle: {
        position: 'absolute',
        bottom: 0,
        flex: 1,
        alignContent: 'center',
        justifyContent: 'center',
        width: 130,
        height: 40,
        backgroundColor: '#051339',
        paddingRight: 0,
        paddingLeft: 0,
        paddingTop: 0,
        paddingBottom: 0,
        fontFamily: "Montserrat-Regular",
        opacity: 0.7
    },
    buttonLq: {
        width: 101,
        height: 47,
        backgroundColor: "#374A66",
        color: "#ffffff",
        justifyContent: "space-around",
        alignItems: "center",
        alignContent: "center",
        flex: 1,
        marginRight: 25,
        borderWidth: 1,
        borderColor: "transparent",
        fontFamily: "Montserrat-Regular",
    },
    buttonLqPress: {
        width: 101,
        height: 47,
        backgroundColor: "#203C66",
        color: "#ffffff",
        justifyContent: "space-around",
        alignItems: "center",
        alignContent: "center",
        flex: 1,
        marginRight: 25,
        borderWidth: 1,
        borderColor: "#BDC6D3",
        shadowColor: '#697E99',
        shadowOffset: { width: 2, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 1,
        fontFamily: "Montserrat-Regular",
    },
    inactiveButton: {
        width: '29%',
        height: 47,
        backgroundColor: "#374A66",
        color: "#ffffff",
        justifyContent: "center",
        alignItems: "center",
        alignContent: "center",
        margin: 8,
        padding: 5,
        borderRadius: 5
    },
    activeButton: {
        width: '29%',
        height: 47,
        backgroundColor: "#203C66",
        color: "#ffffff",
        justifyContent: "center",
        alignItems: "center",
        alignContent: "center",
        margin: 8,
        borderWidth: 1,
        borderColor: "#BDC6D3",
        shadowColor: '#697E99',
        shadowOffset: { width: 2, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 5,
        fontFamily: "Montserrat-Regular",
        padding: 5,
        borderRadius: 5
    },
    buttonRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 25,
    },
    textLq: {
        color: "#ffffff",
        // textAlign: "center",
        fontSize: 11,
        fontFamily: "Montserrat-Regular",
    },
    containerButtonLq: {
        marginLeft: "8%",
        fontFamily: "Montserrat-Regular",
    },
    search: {
        flex: 1,
        fontFamily: "Montserrat-Regular",
        marginTop: 20,
    },
    buttonStyle: {
        width: "39%",
        alignSelf: "center",
        height: 40,
        backgroundColor: "#072D5C",
        // alignItems: 'center',
        // justifyContent: 'center',
        borderRadius: 10,
        // paddingLeft: 40,
        color: "#ffffff",
        zIndex: 0,
        fontFamily: "Montserrat-Regular",
        margin: 5,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.15,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth: 1,
        borderColor: "#BDC6D3",
        shadowColor: '#697E99',

    },
    searchInput: {
        width: "80%",
        alignSelf: "center",
        height: 40,
        backgroundColor: "#072D5C",
        borderRadius: 10,
        paddingLeft: 40,
        color: "#ffffff",
        zIndex: 0,
        fontFamily: "Montserrat-Regular",
    },
    searchInput1: {
        width: '100%',
        alignSelf: "center",
        height: 50,
        backgroundColor: "#072D5C",
        borderRadius: 10,
        paddingLeft: 30,
        color: "#ffffff",
        zIndex: 0,
        fontFamily: "Montserrat-Regular",
    },
    createProjectText1: {
        textAlign: "center",
        opacity: 0.8,
        color: "#ffffff",
        fontSize: 18,
        fontFamily: "Montserrat-Bold",
        // fontWeight: "bold",
    },
    createProjectText2: {
        textAlign: "center",
        opacity: 0.8,
        color: "#ffffff",
        fontSize: 12,
        marginTop: 10,
        fontFamily: "Montserrat-Regular",
        lineHeight: 18
    },
    superScriptText: {
        textAlign: "center",
        opacity: 0.8,
        color: "#ffffff",
        fontSize: 8,
        marginTop: 10,
        fontFamily: "Montserrat-Regular",
        lineHeight: 6
    },
    createProjectText3: {
        textAlign: "center",
        opacity: 0.8,
        color: "#ffffff",
        fontSize: 12,
        marginTop: 5,
        fontFamily: "Montserrat-Regular",
    },
    createProjectText: {
        marginTop: 20,
        marginBottom: 15,
        fontFamily: "Montserrat-Regular",
    },
    nextButton: {
        textAlign: "center",
        width: "80%",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        backgroundColor: "#0078C7",
        fontFamily: "Montserrat-Regular",
    },
    nextButtonText: {
        alignSelf: "center",
        color: "#ffffff",
        fontFamily: "Montserrat-Regular",
    },
    nextButtonWrapper: {
        alignContent: "center",
        justifyContent: "center",
        alignItems: "center",
        justifyContent: "flex-end",
        marginTop: 30,
        fontFamily: "Montserrat-Regular",
    },
    // buttonContent:
    // {
    //     flex: 1,
    // },
    surveyAnsBtn: {
        backgroundColor: "#ffffff",
        alignContent: "center",
        width: "70%",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 25,
        shadowColor: '#cccccc',
        shadowOffset: { width: 2, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 1,
        fontFamily: "Montserrat-Regular",
    },
    surveyAnsBtn1: {
        backgroundColor: "#ffffff",
        alignContent: "center",
        width: "70%",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 25,
        shadowColor: '#cccccc',
        shadowOffset: { width: 2, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 1,
        marginTop: -50,
        fontFamily: "Montserrat-Regular",
    },
    surveyBtnContainer: {
        flex: 1,
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "transparent",
        // marginTop: 40,
        fontFamily: "Montserrat-Regular",
    },
    surveyTextContainer: {
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        paddingBottom: 40,
        fontFamily: "Montserrat-Regular",
    },
    surveyHeading: {
        color: "#ffffff",
        fontSize: 20,
        textAlign: "center",
        // flex:1,
        // marginTop:40,
        // marginLeft:-35,
        fontFamily: "Montserrat-Regular",
        alignSelf: 'center',
    },
    lqHeading: {
        color: "#fefefe",
        fontSize: 14,
        marginBottom: 10,
        fontWeight: "bold",
        fontFamily: "Montserrat-Regular",
        textAlign: 'center'
    },
    surveyQuestion: {
        color: "#fefefe",
        fontSize: 14,
        textAlign: "center",
        fontFamily: "Montserrat-Regular",
    },
    tickEclipseIcons:
    {
        flexDirection: "row",
        fontFamily: "Montserrat-Regular",
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 10,
        marginLeft: 5,
        marginRight: 5
    },
    tickEclipseIcon: {
        marginRight: 16,
        marginTop: 27,
        marginBottom: 32,
        fontFamily: "Montserrat-Regular",
    },
    surveyNextButton:
    {
        backgroundColor: "transparent",
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "Montserrat-Regular",
    },
    surveyNextButtonText: {
        color: "#0078C7",
        textAlign: "center",
        fontWeight: "bold",
        fontFamily: "Montserrat-Regular",
    },
    surveyNextButtonContainer: {
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 100,
        fontFamily: "Montserrat-Regular",
    },
    surveyAnsText: {
        textTransform: "uppercase",
        fontFamily: "Montserrat-Regular",
        color: 'black',
        fontSize: 13
    },
    surveyQuestionBackButton: {
        flexDirection: "row",
        flex: 1,
        fontFamily: "Montserrat-Regular",
    },
    buttonBackSurvey: {
        backgroundColor: "transparent",
        marginTop: 30,
        marginLeft: "8%",
        fontFamily: "Montserrat-Regular",

    },
    surveyNextBtnContainer: {
        marginTop: 10,
        fontFamily: "Montserrat-Regular",
    },
    search1: {
        marginTop: 40,

    },
    imageTextTick: {
        position: "absolute",
        top: 3,
        right: 2,
        width: 14,
        height: 14
    },
    dialogueContent: {
        fontFamily: "Montserrat-Regular",
        backgroundColor: 'transparent',
        // borderWidth: 1,
        // borderRadius: 8,
        // borderColor: "#ffffff",
        // opacity: 1,
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignContent: "center",
        // shadowColor: 'blue',
        // shadowOffset: { width: 5, height: 2 },
        // shadowOpacity: 0.6,
        // shadowRadius: 3,
        // elevation: 1,
    },
    projectName: {
        marginTop: 50,
        fontSize: 17,
        color: "#ffffff",
        textTransform: "uppercase",
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        textAlign: "center",
        fontFamily: "Montserrat-Regular"
    },
    projectNameDesc: {
        marginTop: 15,
        textAlign: "center",
        color: "#ffffff",
        // textTransform: "capitalize",
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        fontFamily: "Montserrat-Regular",
        fontSize: 15
    },
    buttonSave: {
        marginBottom: 20,
        marginTop: 30,
        backgroundColor: "#0078C7",
        width: "100%",
        textAlign: "center",
        justifyContent: "center"
    },
    buttonSkip: {
        backgroundColor: "transparent",
        width: "100%",
        textAlign: "center",
        justifyContent: "center",
    },
    surveyAnsBtn1Clicked: {
        backgroundColor: "#ffffff",
        alignContent: "center",
        width: "70%",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 25,
        shadowColor: '#0078C7B3',
        shadowOffset: { width: 2, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 1,
        marginTop: -50,
        fontFamily: "Montserrat-Regular",
        borderWidth: 2,
        borderColor: "#0078C7",
    },
    surveyAnsBtnClicked: {
        backgroundColor: "#ffffff",
        alignContent: "center",
        width: "70%",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 25,
        shadowColor: '#0078C7B3',
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.7,
        shadowRadius: 4,
        elevation: 4,
        fontFamily: "Montserrat-Regular",
        borderWidth: 1,
        borderColor: "#0078C7",
    },

    earnedHeading: {
        fontSize: 14,
        color: 'white',
        marginTop: 10
    }

})

export default styles