import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    dialogueContent: {
        fontFamily: "Montserrat-Regular",
        backgroundColor: '#051339',
        borderWidth: 1,
        borderRadius: 8,
        borderColor: "#0078C7",
        opacity: 1,
        shadowColor: 'blue',
        shadowOffset: { width: 5, height: 2 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 1,
    },
    textContainer: {
        alignItems: "center",
        alignContent: "center",
    },
    titleStyle: {
        marginTop: 10,
        fontSize: 17,
        color: "#ffffff",
        // textTransform: "uppercase", 
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        textAlign: "center",
        fontFamily: "Montserrat-Regular"
    },
    descStyle: {
        marginTop: 10,
        textAlign: "center",
        color: "#ffffff",
        // textTransform: "lowercase", 
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        fontFamily: "Montserrat-Regular",
        opacity: 0.8
    },
    activeButton: {
        width: '45%',
        height: 47,
        backgroundColor: "#203C66",
        color: "#ffffff",
        justifyContent: "flex-start",
        // alignItems: "center",
        // alignContent: "center",
        // margin: 10,
        borderWidth: 1,
        borderColor: "#BDC6D3",
        shadowColor: '#697E99',
        shadowOffset: { width: 2, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
        elevation: 5,
        fontFamily: "Montserrat-Regular",
        padding: 5,
        paddingLeft: 20,
        borderRadius: 5
    },
    inactiveButton: {
        width: '45%',
        height: 47,
        backgroundColor: "#051339",
        color: "#ffffff",
        justifyContent: "flex-start",
        // alignItems: "center",
        // alignContent: "center",
        // margin: 10,
        padding: 5,
        paddingLeft: 20,
        borderRadius: 5,
        borderColor: '#0078C7',
        borderWidth: 1
    },
    levelText: {
        color: "#ffffff",
        fontSize: 7,
        fontFamily: "Montserrat-Regular",
    },
    levelTextName: {
        color: "#ffffff",
        fontSize: 10,
        fontFamily: "Montserrat-Regular",
    },
    dialogContainer: {
        backgroundColor: 'rgba(5, 19, 57, 0.8)',
        // shadowColor: '#0078C7',
        // shadowOffset: { width: 5, height: 2 },
        // shadowOpacity: 1,
        // shadowRadius: 3,
        // elevation: 5,
        borderWidth: 2,
        borderRadius: 8,
        borderColor: "#0078C7",
        // shadowColor: '#0078C7',
        // shadowOffset: { width: 10, height: 2 },
        // shadowOpacity: 1,
        // shadowRadius: 2,
        // elevation: 1
    },
    viewStyle: {
        alignItems: "center",
        alignContent: "center"
    },
    heading: {
        marginTop: 30,
        fontSize: 17,
        color: "#ffffff",
        textTransform: "uppercase",
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        textAlign: "center",
        fontFamily: "Montserrat-Regular"
    },
    subHeading: {
        marginTop: 10,
        textAlign: "center",
        color: "#ffffff",
        textTransform: "lowercase",
        alignItems: "center",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        fontFamily: "Montserrat-Regular"
    },
    skipButton: { 
        backgroundColor: "transparent", 
        // width: "60%", 
        textAlign: "center", 
        justifyContent: "center",
        display: 'flex',
        flexDirection: 'row',
        alignSelf: 'center',
        alignItems: 'center'
    }
})